#############################################################################
#
#	Makefile for building C++ Unnature on Gumstix ARM Linux
#
#############################################################################
TARGET	= unnature


ifeq ($(DEBUG),y)
	CFLAGS += -O -g		# -O is need to expand inlines
else
  CFLAGS += -O3 #CFLAGS += -O2
endif

PWD     := $(shell pwd)

CC  = gcc
CXX = g++

#
# If you need additional serch paths for include files, then use the -I flag
# and add them to the CPPFLAGS variable
#

# CPPFLAGS += -I somedir

#
# If you need to add C language specific flags, then add them to the CFLAGS variable
#
# If you need to add C++ language specific flags, then add them to the CXXFLAGS variable
#
CXXFLAGS += -Wall -g -D__GXX__ -D__MACOSX_CORE__ -framework CoreAudio -framework CoreMIDI -framework CoreFoundation 

RAWWAVES = rawwaves/
ifeq ($(strip $(RAWWAVES)), )
	RAWWAVES = rawwaves/
endif
CXXFLAGS += -DRAWWAVE_PATH=\"$(RAWWAVES)\"

#
# If you need addional search paths for library files, then use the -L flag
# and add them to LDFLAGS.
#

LDLIBS += -lpthread  -lm 

#
# By default, LINK.o is set to 
#
#     $(CC) $(LDFLAGS) $(TARGET_ARCH)
#
# however, when linking C++ files, we want to use g++ rather than gcc in
# order to get the correct C++ libraries linked in.
#
										
LINK.o = $(CXX) $(LDFLAGS) 

.PHONY: all

all:	depend $(TARGET)

#
# You can change the $(TARGET).c if that's not your main file and you can
# add additional .o files to the end of the line
#

C_SRCS		=
CPP_SRCS	= $(TARGET).cpp Stk.cpp Instrmnt.cpp WvIn.cpp FileRead.cpp FileWvIn.cpp Filter.cpp OnePole.cpp Generator.cpp SineWave.cpp RtAudio.cpp Message.cpp Speaker.cpp Genome.cpp Organism.cpp Conductor.cpp Rand.cpp Dispatcher.cpp Anuran.cpp SpringPeeper.cpp GrayTreeFrog.cpp BirdVoicedTreeFrog.cpp GreenFrog.cpp GreenTreeFrog.cpp AmericanToad.cpp BullFrog.cpp BrimleysChorusFrog.cpp EasternNarrowmouthToad.cpp PickerelFrog.cpp Cricket.cpp AllardsGroundCricket.cpp GreaterAnglewing.cpp SnowyTreeCricket.cpp CommonMeadowKatydid.cpp SpringGroundCricket.cpp Breeder.cpp


# You shouldnt have to mess with this section yet
#
# You can change the $(TARGET).c if that's not your main file and you can
# add additional .o files to the end of the line
#


OBJS		= $(CPP_SRCS:.cpp=.o) $(C_SRCS:.c=.o)
		     
$(TARGET) : $(OBJS)

clean:
	rm -rf $(OBJS) core .depend $(TARGET)

depend .depend dep:
	rm -f .depend
ifneq ($(CPP_SRCS),)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -M $(src/CPP_SRCS) >> .depend
endif
ifneq ($(C_SRCS),)
	$(CC) $(CFLAGS) $(CPPFLAGS) -M $(C_SRCS) >> .depend
endif

ifeq (.depend,$(wildcard .depend))
include .depend
endif
